name: Unit Test
on:
  push:
    paths:
      - 'backend/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Lint
        run: cd backend && npm i && npm run lint --if-present
